version: '3'
services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    image: zoocasa-scraper
    command: "scrapy crawl zoocasa -o 'scraped-data.csv'"
    volumes:
      - .:/app